# ==============================================================================
# FILE: blueprints/game.py
# Game Blueprint: game hub, memory, millionaire, sentence builder
# ==============================================================================

import os
import re
import json

from flask import Blueprint, render_template, request, jsonify, session

from models import (
    get_db, Topic, GameQuestion, GameSession, PracticeQuestion,
)
from blueprints.helpers import login_required, _get_topic_or_404, _json_error

game_bp = Blueprint("game", __name__)


# ==============================================================================
# Shared Helpers (game-specific)
# ==============================================================================
def _topic_slides_obj(topic):
    """Parse topic['slides_json'] into dict. Always returns dict."""
    try:
        raw = topic.get("slides_json") or ""
        obj = json.loads(raw) if raw else {}
        if isinstance(obj, list):
            return {"slides": obj}
        if isinstance(obj, dict):
            return obj
    except Exception:
        pass
    return {"slides": []}


def _topic_get_sentence_builder_custom(topic):
    obj = _topic_slides_obj(topic)
    items = obj.get("sentence_builder_custom") or []
    out = []
    if isinstance(items, list):
        for it in items:
            if isinstance(it, dict):
                th = (it.get("th") or "").strip()
                en = (it.get("en") or "").strip()
                if th or en:
                    out.append({"th": th, "en": en})
    return out


def _topic_save_sentence_builder_custom(topic_id, items):
    topic = Topic.get_by_id(topic_id)
    if not topic:
        return False
    obj = _topic_slides_obj(topic)
    cleaned = []
    if isinstance(items, list):
        for it in items:
            if not isinstance(it, dict):
                continue
            th = (it.get("th") or "").strip()
            en = (it.get("en") or "").strip()
            if not th and not en:
                continue
            cleaned.append({"th": th[:500], "en": en[:500]})
    obj["sentence_builder_custom"] = cleaned
    Topic.update(topic_id, topic["name"], topic.get("description") or "", json.dumps(obj, ensure_ascii=False), topic.get("pdf_file"))
    return True


def _normalize_practice_questions(rows):
    """Normalize practice question rows — parse JSON question field into prompt + choices."""
    out = []
    for r in rows:
        q = dict(r)
        prompt, choices = "", []
        raw = q.get("question") or ""
        try:
            obj = json.loads(raw)
            if isinstance(obj, dict):
                prompt = (obj.get("prompt") or "").strip()
                choices = [str(x) for x in (obj.get("choices") or [])]
            else:
                prompt = str(obj)
        except Exception:
            prompt = str(raw)
        out.append({
            "id": q.get("id"),
            "prompt": prompt,
            "choices": choices,
            "correct_answer": q.get("correct_answer") or "",
        })
    return out


def _get_practice_data_from_slides(topic):
    """
    Extract vocabulary, examples, dialogues, and game questions from topic.
    Returns a dict with keys: vocabulary, examples, dialogues, questions.
    Supports all slide types generated by ai_generator.py:
      hook, objectives, context, vocabulary, examples,
      guided_practice, dialogue, production, review, exit_ticket
    """
    data = {"vocabulary": [], "examples": [], "dialogues": [], "questions": []}

    if topic.get("slides_json"):
        try:
            obj = json.loads(topic["slides_json"])
            slides = obj.get("slides", obj) if isinstance(obj, dict) else obj
            if not isinstance(slides, list):
                slides = []

            for slide in slides:
                if not isinstance(slide, dict):
                    continue
                slide_type = slide.get("type", "")

                # --- Vocabulary slides ---
                if slide_type == "vocabulary":
                    for v in (slide.get("vocabulary") or []):
                        if isinstance(v, dict) and v.get("word") and v.get("meaning"):
                            data["vocabulary"].append({
                                "word": v["word"],
                                "meaning": v["meaning"],
                                "example": v.get("example", ""),
                                "ipa": v.get("ipa", ""),
                            })

                # --- Examples slides (and any slide that has "examples" key) ---
                if slide.get("examples"):
                    for ex in slide["examples"]:
                        if isinstance(ex, dict):
                            en = (ex.get("en") or ex.get("sentence") or ex.get("text") or "").strip()
                            th = (ex.get("th") or "").strip()
                            if en:
                                data["examples"].append({"en": en, "th": th})
                        elif isinstance(ex, str) and ex.strip():
                            data["examples"].append({"en": ex.strip(), "th": ""})

                # --- Dialogue slides ---
                if slide_type == "dialogue" and slide.get("lines"):
                    for line in slide["lines"]:
                        if isinstance(line, dict) and line.get("text"):
                            data["dialogues"].append({
                                "speaker": line.get("speaker", ""),
                                "text": line["text"],
                            })
        except Exception:
            pass

    # --- Game tile questions ---
    for set_no in range(1, 4):
        qs = GameQuestion.get_by_topic_and_set(topic["id"], set_no)
        for q in qs:
            data["questions"].append({
                "question": q["question"],
                "answer": q["answer"],
            })

    return data


def _enrich_examples_with_th(game_data):
    """
    Ensure examples have Thai translations for Sentence Builder.
    Priority order:
      1. Keep existing Thai from examples (already have th field)
      2. Synthesize from vocabulary: use vocabulary example sentence + Thai meaning
      3. Try OpenAI translation as last resort (optional, won't break if fails)
    No API call is made unless examples truly have no Thai at all.
    """
    if not game_data or not isinstance(game_data, dict):
        return game_data

    examples = game_data.get("examples") or []
    vocabulary = game_data.get("vocabulary") or []

    # Build vocab lookup: English example sentence → Thai meaning
    vocab_en_to_th = {}
    for v in vocabulary:
        ex_en = (v.get("example") or "").strip()
        meaning = (v.get("meaning") or "").strip()
        if ex_en and meaning and re.search(r"[ก-๙]", meaning):
            vocab_en_to_th[ex_en.lower()] = meaning

    # Also build vocab lookup: word → meaning (for short-sentence matching)
    vocab_word_to_meaning = {}
    for v in vocabulary:
        word = (v.get("word") or "").strip().lower()
        meaning = (v.get("meaning") or "").strip()
        if word and meaning and re.search(r"[ก-๙]", meaning):
            vocab_word_to_meaning[word] = meaning

    new_examples = []
    still_missing = []

    for ex in examples:
        if not isinstance(ex, dict):
            continue
        en = (ex.get("en") or "").strip()
        th = (ex.get("th") or "").strip()

        if not en:
            continue

        has_thai = bool(th and re.search(r"[ก-๙]", th))

        if has_thai:
            # Already has Thai — keep as-is
            new_examples.append({"en": en, "th": th})
        else:
            # Try vocab lookup by exact sentence match
            th_from_vocab = vocab_en_to_th.get(en.lower(), "")
            if th_from_vocab:
                new_examples.append({"en": en, "th": th_from_vocab})
            else:
                # Keep for AI translation batch
                new_examples.append({"en": en, "th": ""})
                still_missing.append(en)

    # If some examples still lack Thai, try AI translation
    if still_missing:
        translated = _ai_translate_batch(still_missing)
        mapping = {t["en"].strip().lower(): t["th"] for t in translated if t.get("en") and t.get("th")}
        for ex in new_examples:
            if not ex["th"] and ex["en"].lower() in mapping:
                ex["th"] = mapping[ex["en"].lower()]

    # Append vocabulary example sentences as bonus sentences (if not already there)
    existing_en = {e["en"].lower() for e in new_examples}
    for v in vocabulary:
        ex_en = (v.get("example") or "").strip()
        meaning = (v.get("meaning") or "").strip()
        if ex_en and meaning and re.search(r"[ก-๙]", meaning):
            if ex_en.lower() not in existing_en:
                new_examples.append({"en": ex_en, "th": meaning})
                existing_en.add(ex_en.lower())

    game_data["examples"] = new_examples
    return game_data


def _ai_translate_batch(sentences):
    """
    Translate a list of English sentences to Thai using OpenAI.
    Returns list of {en, th} dicts. Safe to call — returns [] on any failure.
    """
    if not sentences:
        return []
    api_key = os.environ.get("OPENAI_API_KEY") or os.environ.get("OPENAI_APIKEY") or os.environ.get("OPENAI_KEY")
    if not api_key:
        return []
    try:
        from openai import OpenAI
        client = OpenAI(api_key=api_key)
        payload = json.dumps({
            "task": "translate_en_to_th",
            "rules": [
                "Translate each English sentence to natural Thai for students.",
                "Return ONLY a JSON array: [{\"en\":...,\"th\":...}, ...]",
                "Same order as input. No extra text.",
            ],
            "sentences": sentences[:40],
        }, ensure_ascii=False)
        resp = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You translate English to Thai. Return ONLY valid JSON array, no markdown."},
                {"role": "user", "content": payload},
            ],
            temperature=0.2,
            max_tokens=2000,
        )
        content = (resp.choices[0].message.content or "").strip()
        # Extract JSON array
        start = content.find("[")
        end = content.rfind("]")
        if start != -1 and end != -1:
            arr = json.loads(content[start:end + 1])
            if isinstance(arr, list):
                return [{"en": str(t.get("en", "")).strip(), "th": str(t.get("th", "")).strip()}
                        for t in arr if isinstance(t, dict) and t.get("en") and t.get("th")]
    except Exception:
        pass
    return []


# ==============================================================================
# Game Hub
# ==============================================================================
@game_bp.route("/topic/<int:topic_id>/game")
@login_required
def game(topic_id):
    topic = _get_topic_or_404(topic_id)
    last_session = GameSession.get_latest_by_topic_and_user(topic_id, session["user_id"])
    return render_template("game.html", topic=topic, last_session=last_session)


# ==============================================================================
# Game APIs: sets & sessions
# ==============================================================================
@game_bp.route("/api/game/<int:topic_id>/sets")
@login_required
def api_game_sets(topic_id):
    _get_topic_or_404(topic_id)
    sets_data = {}
    for set_no in range(1, 4):
        questions = GameQuestion.get_by_topic_and_set(topic_id, set_no)
        if questions:
            sets_data[str(set_no)] = [
                {"id": q["id"], "tile_no": q["tile_no"], "question": q["question"], "answer": q["answer"], "points": q["points"]}
                for q in questions
            ]
    return jsonify(sets_data)


@game_bp.route("/api/game/<int:topic_id>/sessions", methods=["GET", "POST"])
@login_required
def api_game_sessions(topic_id):
    _get_topic_or_404(topic_id)
    if request.method == "GET":
        return jsonify({"ok": True, "sessions": GameSession.get_by_topic(topic_id)})
    data = request.get_json(silent=True) or {}
    sess = GameSession.create(topic_id, session["user_id"], data.get("title") or "Session", json.dumps(data.get("settings") or {}), json.dumps(data.get("state") or {}))
    return jsonify({"ok": True, "session": sess})


@game_bp.route("/api/game/session/<int:session_id>")
@login_required
def api_game_session_get(session_id):
    sess = GameSession.get_by_id(session_id)
    return jsonify({"ok": True, "session": sess}) if sess else _json_error("Not found", 404)


@game_bp.route("/api/game/session/<int:session_id>/save", methods=["POST"])
@login_required
def api_game_session_save(session_id):
    sess = GameSession.get_by_id(session_id)
    if not sess:
        return _json_error("Not found", 404)
    data = request.get_json(silent=True) or {}
    GameSession.update(session_id, data.get("title") or sess["title"], json.dumps(data.get("settings") or {}), json.dumps(data.get("state") or {}))
    return jsonify({"ok": True})


# ==============================================================================
# Memory Match Game
# ==============================================================================
@game_bp.route("/topic/<int:topic_id>/game/memory")
@login_required
def game_memory(topic_id):
    topic = _get_topic_or_404(topic_id)

    vocabulary = []
    if topic.get("slides_json"):
        try:
            obj = json.loads(topic["slides_json"])
            slides = obj.get("slides", obj) if isinstance(obj, dict) else obj
            for slide in slides:
                if slide.get("type") == "vocabulary" and slide.get("vocabulary"):
                    for v in slide["vocabulary"]:
                        if v.get("word") and v.get("meaning"):
                            vocabulary.append({"word": v["word"], "meaning": v["meaning"]})
        except Exception:
            pass

    questions = []
    for set_no in range(1, 4):
        qs = GameQuestion.get_by_topic_and_set(topic_id, set_no)
        for q in qs:
            questions.append({"question": q["question"], "answer": q["answer"]})

    game_data = {"vocabulary": vocabulary, "questions": questions}
    return render_template("game_memory.html", topic=topic, game_data=game_data)


# ==============================================================================
# Millionaire Game
# ==============================================================================
@game_bp.route("/topic/<int:topic_id>/game/millionaire")
@login_required
def game_millionaire(topic_id):
    topic = _get_topic_or_404(topic_id)
    questions = _normalize_practice_questions(PracticeQuestion.get_by_topic(topic_id))
    return render_template("game_millionaire.html", topic=topic, questions=questions)


# ==============================================================================
# Sentence Builder Game
# ==============================================================================
@game_bp.route("/api/topic/<int:topic_id>/sentence-builder/custom", methods=["GET", "POST"])
@login_required
def api_sentence_builder_custom(topic_id):
    topic = _get_topic_or_404(topic_id)
    if request.method == "GET":
        return jsonify({"ok": True, "items": _topic_get_sentence_builder_custom(topic)})
    data = request.get_json(silent=True) or {}
    items = data.get("items") or []
    ok = _topic_save_sentence_builder_custom(topic_id, items)
    return jsonify({"ok": bool(ok), "items": _topic_get_sentence_builder_custom(Topic.get_by_id(topic_id))})


@game_bp.route("/topic/<int:topic_id>/game/sentence-builder")
@login_required
def game_sentence_builder(topic_id):
    topic = _get_topic_or_404(topic_id)

    # Build game_data dict with vocabulary + examples + dialogues + game tile questions
    game_data = _get_practice_data_from_slides(topic)

    # Ensure examples have Thai translations (uses vocab lookup + AI fallback)
    game_data = _enrich_examples_with_th(game_data)

    # Get students linked to this topic via classroom assignments
    students = []
    conn = get_db()
    c = conn.cursor()
    c.execute("""
        SELECT DISTINCT cs.student_name
        FROM classroom_students cs
        JOIN assignments a ON a.classroom_id = cs.classroom_id
        WHERE a.topic_id = ?
        ORDER BY cs.student_no, cs.student_name
    """, (topic_id,))
    rows = c.fetchall()
    conn.close()
    students = [r["student_name"] for r in rows] if rows else []

    return render_template("game_sentence_builder.html", topic=topic, game_data=game_data, students=students)
